### PR TITLE
add mesh_objects directory.. a transient directory

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
i was going to reuse the bpy obj loader, but this generates a scene object. ie, there's no functions exposed that can be imported to go from filepath->pydata without editing the code. so a simple/stupid loader might be of interest.

**Comment by zeffii** [comment]
```python
import os

from svrx.util.geom import generator
from svrx.util.mesh import rxdata_from_pydata

def simple_obj_loader(path):
    verts, edges, faces = [], [] ,[]
    add_vert = verts.append
    add_face = faces.append
    with open(path) as ofile:
        for line in ofile:
            if line.startswith('v'):
                add_vert([float(i) for i in line[2:].strip().split(' ')])
            if line.startswith('f'):
                add_face([int(i)-1 for i in line[2:].strip().split(' ')])
    
    return verts, edges, faces


@node_script
@generator
def sn_make_cricket(dummy: Int = 3) -> ([Vertices], [Edges], [Faces]):
    mesh_objects_path = r"C:\Users\zeffi\Desktop\GITHUB\DEEP\svrx\util\mesh_objects"
    obj_path = os.path.join(mesh_objects_path, "cricket.obj")
    verts, _, faces = simple_obj_loader(obj_path)
    return rxdata_from_pydata(verts, faces=faces)

```

notice currently a dummy value is needed for the params, else

```
  File "svrx\core\handler.py", line 37, in sv_main_handler
    ng.execute()
  File "svrx\core\tree.py", line 45, in execute
    exec_node_group(self)
  File "svrx\core\execution.py", line 301, in exec_node_group
    recurse_levels(func, in_levels , [l for _, l in func.returns], in_trees, out_trees)
  File "svrx\core\execution.py", line 221, in recurse_levels
    results = f(*args)
  File "svrx\util\geom.py", line 114, in inner
    for param in match(*parameters, limit=limit, mask=mask):
  File "svrx\util\geom.py", line 48, in match_long_repeat
    max_len = max(counts)
ValueError: max() arg is an empty sequence
```

`@generator` isn't expecting zero arguments

**Comment by ly29** [comment]
If you take zero arguments you don't need to be a generator.

There are rules but isn't any documentation, will try to write a bit tomorrow.

**Comment by ly29** [comment]
@zeffii 
Also if you in problems just ask, I mean at this point there is something like 60/40 chance it is a bug/systematic issue.

**Comment by ly29** [comment]
But a simple loader is nice, could even use a zip file and cache the result with ```@functools.lru_cache```

**Comment by ly29** [comment]
the caching is probably more important. drag a slider and open and load file 10 times a second or so, I mean the file will be cached so the disk won't be touched but feels a bit heavy.

**Comment by zeffii** [comment]
that is one thing i meant to bring up, caching. like a frozen node.. that never does work expect output the last-processed-time

**Comment by ly29** [comment]
Efficient caching and more clever execution is a bit down the line, but I really want to rethink the amount of calculations we do.

**Pull request merged**
