### PR TITLE
prelim push of bgl_callback_3dview_2d

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Review by ly29 — COMMENTED** [review]
:smile:

**Comment by zeffii** [comment]
i'd like to merge this now

**Comment by zeffii** [comment]
experiments with index hiding determined by Normals might follow. worth doing anyway, As it stands this gives some insight into new geometry and writing the custom function of the callback.

**Comment by ly29** [comment]
Go ahead and merge.

**Pull request merged**
