### PR TITLE
S mesh from pydata

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
untested.. will have try with SN later :)

**Comment by ly29** [comment]
Stick some ```@classmethod``` in there also

**Comment by zeffii** [comment]
for SMesh maybe

def from_pydata(cls, pydata)

def from_pydata(cls, verts, edges=None, faces=None):

?

**Comment by zeffii** [comment]
else it's always  `smesh = SMesh.from_pydata(verts, [], [])`

**Comment by zeffii** [comment]
uchh.. gotta go

**Comment by ly29** [comment]
It reflects what is needed.
```python
def from_pydata(cls, verts, edges=None, faces=None):
```

**Comment by zeffii** [comment]
cool.

**Comment by zeffii** [comment]
now...to test this on some unsuspecting generator..

**Comment by zeffii** [comment]
time for bed. longer day ahead tomorrow :/

**Pull request merged**
