### PR TITLE
Sn additions

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
these classes as tested well in N1 , snlite :)    but RXscript is having a minor heart palputation with `.ext` in filenames as you know.

**Comment by ly29** [comment]
Yeah it is easy workaround possible, basically a dictionary mapping sanitized names to the real names. Just haven't decided where to put it yet. 
Will take care of it tomorrow.

**Comment by ly29** [comment]
The code already exists even, just linking it up as needed...

**Comment by zeffii** [comment]
i also renamed the callback class - just in case :)

**Comment by zeffii** [comment]
i also renamed the callback class - just in case :)

```diff
- class SvScriptNodeLiteCallBack(bpy.types.Operator):
+ class SvRxScriptNodeCallBack(bpy.types.Operator):
```

**Comment by ly29** [comment]
I noticed, good call. Allowing .py names should be up soon

**Pull request merged**
