### PR TITLE
Mesh output mk1

### PR DESCRIPTION
**Pull request by zeffii**
experimenting

### CODE REVIEW

**Comment by ly29** [comment]
Good luck, I suspect there might be issues. But hopefully it will work out. 

:)

Anyway will take look tomorrow.

**Comment by zeffii** [comment]
it's late i've noticed, this is not the best time for me to write code :)

**Comment by ly29** [comment]
I was thinking it would be good to refactor so allow  bmesh or other mesh types input also. So the code for object creation and management is separate, maybe not now but allow the idea.

**Comment by portnov** [comment]
Yes, most probably we will need some type of "mesh" socket. Because many existing nodes in current Sverchok work with BMesh internally, there is no point in converitng list -> bmesh -> list -> bmesh...

**Comment by ly29** [comment]
@portnov 
I totally agree

**Comment by zeffii** [comment]
totally, certain chains of nodes probably will benefit from staying as bm entirely.

**Comment by ly29** [comment]
@zeffii 
Since the last commit is hulk angry I feel a bit hesitant about merging, however will fix any problems in master anyway. much better than what there before...

**Comment by zeffii** [comment]
> Since the last commit is hulk angry I feel a bit hesitant about merging 

haha yes, and rightfully so. I notice that the obj's are unlinked from scene before refilling their meshes. (ie here the mesh disappears from the outliner, in a way that doesn't happen in Sverchok..) I didn't have time to track down why.  maybe today.

**Comment by zeffii** [comment]
image

**Pull request merged**
