### PR TITLE
added more vmath modes

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
I didn't pull before adding these commits.. will resolve soon.

**Comment by zeffii** [comment]
(untested)

**Comment by ly29** [comment]
The type should probably be Vector but this part probably needs to be adjusted anyway

**Comment by zeffii** [comment]
it feels a little verbose with all these nodefuncs

**Comment by ly29** [comment]
I agree. Especially for small nodes like this and math.
But looking at bigger codebases this amount of verbosity ain't that bad. 

I have some ideas...

**Comment by zeffii** [comment]
Yes, for nodes with just 2 or 3..4 modes, this can be neat. -- it is only with these large mode numbers that it seems there could be a more succinct way. 

Even though perhaps if modes use a lot of shared code, i'd still prefer to write them a bit more 'manually'.

**Comment by ly29** [comment]
Just getting rid of the bl_idname for multi nodes would make cleaner but I have some further ideas. But compare to the boilerplate in an old node...

But the tables with functions are prettier than this.

**Comment by zeffii** [comment]
not a top priority really, these larger mode counts are uncommon. Don't pay much attention to my comment above

**Comment by zeffii** [comment]
haven't had time to resolve the conflicts here,  maybe lateron tonight.

**Comment by ly29** [comment]
Would be great if we could solve the last nodes for basic level and then start to play a bit more with it to find systematic problems to fix.

**Comment by zeffii** [comment]
Agreed. I think quite a few nodes can be written easily with this mechanism

**Comment by zeffii** [comment]
not too proud of having two nodes in the one pull request.. but it happened :/

**Comment by zeffii** [comment]
i removed PI from math node, because it is already in Trig node,  perhaps a smaller constants node would make sense (even if it includes some overlap)

**Pull request merged**
